name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install cpplint and upgrade CMake
        run: |
          sudo apt-get remove --purge -y cmake
          python3 -m pip install --upgrade pip
          python3 -m pip install cpplint
          python3 -m pip install cmake --upgrade

      - name: Cache third-party dependencies
        uses: actions/cache@v4
        with:
          path: build/third_party
          key: ${{ runner.os }}-third-party-${{ hashFiles('cmake/spot.cmake', 'cmake/ganak.cmake') }}
          restore-keys: |
            ${{ runner.os }}-third-party-

      - name: Configure project
        run: cmake --preset debug

      - name: Check formatting
        run: cmake --build --preset debug --target format-ci

      - name: Check linting
        run: cmake --build --preset debug --target lint

      - name: Build project
        run: cmake --build --preset debug

      - name: Run tests
        run: ctest --preset debug
